### ISSUE TITLE
MemoryProfiler throws ExceptionInInitializerError

### ISSUE THREAD

**Issue by stelfrich** [fiji/fiji-compat#4]
Executing `./ImageJ-macosx --main-class fiji.MemoryProfiler fiji.Main` throws exception about ImageJ1 patching:

```
MemoryProfiler: 2160 2428136 org.scijava.util.FileUtils$1.accept(FileUtils.java:208)
[...]many of those lines[...]
MemoryProfiler: -18104 3903416 net.imagej.patcher.Utils.getLocation(Utils.java:129)
MemoryProfiler: -3648 3906096 net.imagej.patcher.CodeHacker.javaAgentHint(CodeHacker.java:828)
Error while executing the main() method of class 'fiji.MemoryProfiler':
java.lang.ExceptionInInitializerError
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at javassist.Loader.run(Loader.java:288)
	at fiji.MemoryProfiler.main(MemoryProfiler.java:119)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.imagej.launcher.ClassLauncher.launch(ClassLauncher.java:279)
	at net.imagej.launcher.ClassLauncher.run(ClassLauncher.java:186)
	at net.imagej.launcher.ClassLauncher.main(ClassLauncher.java:77)
Caused by: java.lang.RuntimeException: No _hooks field found in ij.IJ
It appears that this class was already defined in the class loader!
Please make sure that you initialize the LegacyService before using
any ImageJ 1.x class. You can do that by adding this static initializer:

	static {
		LegacyInjector.preinit();
	}

To debug this issue, start the JVM with the option:

	-javaagent:/Applications/Fiji.app/jars/ij1-patcher-0.12.6.jar

To enforce pre-initialization, start the JVM with the option:

	-javaagent:/Applications/Fiji.app/jars/ij1-patcher-0.12.6.jar=init

	at net.imagej.patcher.CodeHacker.javaAgentHint(CodeHacker.java:828)
	at net.imagej.patcher.LegacyInjector.alreadyPatched(LegacyInjector.java:433)
	at net.imagej.patcher.LegacyInjector.preinit(LegacyInjector.java:380)
	at net.imagej.patcher.LegacyInjector.preinit(LegacyInjector.java:376)
	at fiji.IJ1Patcher.run(IJ1Patcher.java:37)
	at fiji.Main.<clinit>(Main.java:30)
	... 13 more
Caused by: java.lang.RuntimeException: Unexpected type of ij.IJ._hooks: class net.imagej.patcher.LegacyHooks (loader: sun.misc.Launcher$AppClassLoader@764c12b6)
	at net.imagej.patcher.LegacyInjector.alreadyPatched(LegacyInjector.java:427)
	... 17 more
```

Reported and discussed in http://forum.imagej.net/t/memoryprofiler-on-macos/5982.

**Comment by stelfrich** [comment]
It seems that the issue is due to a failing check if `ij.IJ` has already been patched in [LegacyInjector.java#L425](https://github.com/imagej/ij1-patcher/blob/master/src/main/java/net/imagej/patcher/LegacyInjector.java#L425). Attempts to work around the issue, i.e. https://github.com/stelfrich/fiji-compat/commit/1500ce69de19dbdad8145ce6d61895a230720172 and https://github.com/imagej/ij1-patcher/commit/0df01b94c5f4f10f9df5f52247d0e8172f9b0bbd, were not successful.

**Comment by ctrueden** [comment]
The fiji-compat component is now obsolete. The `MemoryProfiler` moved to ij1-patcher as of imagej/ij1-patcher@76af08f4a581ca227dcc7f094ab8b75c4a153518. This issue is still going to be relevant, since the code didn't change. But due to lack of bandwidth, I'm closing the issue for now. If anyone wants to fix up the `MemoryProfiler`, they are still welcome to do so.
